/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A person instructing a Class
type ClassInstructor struct {
	// Course identifier number, not unique
	CourseId string `json:"courseId,omitempty"`
	// Course offer number identifier for this class
	CourseOfferNumber int32 `json:"courseOfferNumber,omitempty"`
	// Session code number for this class
	SessionCode string `json:"sessionCode,omitempty"`
	// Number identifying the section of this class
	ClassSection int32 `json:"classSection,omitempty"`
	// Waterloo academic term code
	TermCode string `json:"termCode,omitempty"`
	// REMOVED for privacy. The code designation for the instructor's role in this class
	InstructorRoleCode string `json:"instructorRoleCode,omitempty"`
	// REMOVED for privacy. The Instructors preferred first name
	InstructorFirstName string `json:"instructorFirstName,omitempty"`
	// REMOVED for privacy. The Instructors preferred last name
	InstructorLastName string `json:"instructorLastName,omitempty"`
	// REMOVED for privacy. A unique identifier that persists through name changes. Not guaranteed, but likely to be immutable for instructor.
	InstructorUniqueIdentifier string `json:"instructorUniqueIdentifier,omitempty"`
	// Identifier for the class meeting this instructor is for
	ClassMeetingNumber int32 `json:"classMeetingNumber,omitempty"`
}
