/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents an Academic class, which is a scheduled instance of a Course
type Class struct {
	// Course identifier number, not unique
	CourseId string `json:"courseId,omitempty"`
	// Course offer number identifier for this class
	CourseOfferNumber int32 `json:"courseOfferNumber,omitempty"`
	// Session code for this class
	SessionCode string `json:"sessionCode,omitempty"`
	// Number identifying the section of this class
	ClassSection int32 `json:"classSection,omitempty"`
	// Waterloo academic term code
	TermCode string `json:"termCode,omitempty"`
	// Class number identifier for this class
	ClassNumber int32 `json:"classNumber,omitempty"`
	// Course component code for this class
	CourseComponent string `json:"courseComponent,omitempty"`
	// Associated class code for this class
	AssociatedClassCode int32 `json:"associatedClassCode,omitempty"`
	// Indicates the maximum number of students that can enroll in this class
	MaxEnrollmentCapacity int32 `json:"maxEnrollmentCapacity,omitempty"`
	// Indicates the current number of students enrolled in this class
	EnrolledStudents int32 `json:"enrolledStudents,omitempty"`
	// Code describing whether No, Instructor, or Department consent to enroll is required. Overrides Course level information if different.
	EnrollConsentCode string `json:"enrollConsentCode,omitempty"`
	// Description of the enroll requirement. Overrides Course level information if different.
	EnrollConsentDescription string `json:"enrollConsentDescription,omitempty"`
	// Code describing whether No, Instructor, or Department consent to drop is required. Overrides Course level information if different.
	DropConsentCode string `json:"dropConsentCode,omitempty"`
	// Description of the drop requirement. Overrides Course level information if different.
	DropConsentDescription string `json:"dropConsentDescription,omitempty"`
	// Schedule data for this class
	ScheduleData []ClassSchedule `json:"scheduleData,omitempty"`
	// Instructor data for this class
	InstructorData []ClassInstructor `json:"instructorData,omitempty"`
}
