/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OutletType struct {
	Tid string `json:"tid,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
}
