/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Model representing News data associated to a Site in the WCMS
type SiteNews struct {
	// Unique, numeric site ID of the Site this news originates from
	SiteId int32 `json:"siteId,omitempty"`
	// Unique Id of this news item
	UniqueKey string `json:"uniqueKey,omitempty"`
	// Title of the news item
	Title string `json:"title,omitempty"`
	// Content created or posted date
	PostedDate time.Time `json:"postedDate,omitempty"`
	// Content updated date
	UpdatedDate time.Time `json:"updatedDate,omitempty"`
	// URI to the news item in WCMS
	ItemUri string `json:"itemUri,omitempty"`
	// Intended audience tag(s)
	Audience string `json:"audience,omitempty"`
	// News item content, often with HTML markup
	Content string `json:"content,omitempty"`
}
