/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Feature of location collection
type Feature struct {
	// Type of Feature
	Type_ string `json:"type,omitempty"`
	Properties *Location `json:"properties,omitempty"`
	Geometry *Geometry `json:"geometry,omitempty"`
}
