/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FoodServicesOutlets struct {
	Data []FoodServicesOutlet `json:"data,omitempty"`
	Count int32 `json:"count,omitempty"`
	Self *FoodServicesOutletsSelf `json:"self,omitempty"`
}
