/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Details about terms, dates, and special notes for an Important Date
type ImportantDateDetails struct {
	// Id link to associated Important Date, internal
	ImportantDateId int32 `json:"importantDateId,omitempty"`
	// Id to the associated Term
	TermId int32 `json:"termId,omitempty"`
	// Name of the associated Term when the Important Date takes place
	TermName string `json:"termName,omitempty"`
	// Start or event date for the Important Date
	StartDate time.Time `json:"startDate,omitempty"`
	// Optional end date for the Important Date
	EndDate time.Time `json:"endDate,omitempty"`
	// Any special notes for this occurance of the Important Date, can contain markup
	Notes string `json:"notes,omitempty"`
}
