/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Model representing a WCMS blog post item
type SiteBlogPost struct {
	// Unique, numeric site ID
	SiteId int32 `json:"siteId,omitempty"`
	// Unique Id of this post item
	UniqueKey string `json:"uniqueKey,omitempty"`
	// Title of the blog post
	Title string `json:"title,omitempty"`
	// Content created or posted date
	PostedDate time.Time `json:"postedDate,omitempty"`
	// Content updated date
	UpdatedDate time.Time `json:"updatedDate,omitempty"`
	// URI to the item in WCMS
	ItemUri string `json:"itemUri,omitempty"`
	// Intended audience tag(s)
	Audience string `json:"audience,omitempty"`
	// Blog post content, often with HTML markup
	Content string `json:"content,omitempty"`
	// Display name of the delegated author for this blog post
	DelegatedAuthorName string `json:"delegatedAuthorName,omitempty"`
	// Link to the WCMS profiel of the delegated author
	DelegatedAuthorUri string `json:"delegatedAuthorUri,omitempty"`
	// Username of the person publishing the content, not necessarily the author
	PublisherUsername string `json:"publisherUsername,omitempty"`
}
