/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OpeningHour struct {
	Day string `json:"day,omitempty"`
	Starthours string `json:"starthours,omitempty"`
	Endhours string `json:"endhours,omitempty"`
	Comment string `json:"comment,omitempty"`
}
