/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Logo struct {
	Id string `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Filemime string `json:"filemime,omitempty"`
	Filesize string `json:"filesize,omitempty"`
	Width string `json:"width,omitempty"`
	Height string `json:"height,omitempty"`
	Alt string `json:"alt,omitempty"`
	Title string `json:"title,omitempty"`
}
