/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Combo struct {
	Name string `json:"name,omitempty"`
	Image *ComboImage `json:"image,omitempty"`
	Options string `json:"options,omitempty"`
	Item string `json:"item,omitempty"`
	Price string `json:"price,omitempty"`
	Calories *Object `json:"calories,omitempty"`
}
