/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Current struct {
	Hid string `json:"hid,omitempty"`
	Vid string `json:"vid,omitempty"`
	Nid string `json:"nid,omitempty"`
	FromState string `json:"from_state,omitempty"`
	State string `json:"state,omitempty"`
	Uid string `json:"uid,omitempty"`
	Stamp string `json:"stamp,omitempty"`
	Published string `json:"published,omitempty"`
	IsCurrent int32 `json:"is_current,omitempty"`
	Title string `json:"title,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
}
