/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Model representing a WCMS Event item
type SiteEvent struct {
	// Unique, numeric site ID
	SiteId int32 `json:"siteId,omitempty"`
	// Unique Id of this evevnt item
	UniqueKey string `json:"uniqueKey,omitempty"`
	// Title of the event
	Title string `json:"title,omitempty"`
	// Start date of the event
	EventStartDate time.Time `json:"eventStartDate,omitempty"`
	// End date of the event
	EventEndDate time.Time `json:"eventEndDate,omitempty"`
	// Description of the event recurrence rule
	RecurRule string `json:"recurRule,omitempty"`
	// Time zone description of the event dates
	EventTimezone string `json:"eventTimezone,omitempty"`
	// Link to the Event
	ItemUri string `json:"itemUri,omitempty"`
	// Tag(s) representing the event
	EventTags string `json:"eventTags,omitempty"`
	// Type of the event
	EventType string `json:"eventType,omitempty"`
	// Supplemental URI for the event
	EventWebsite string `json:"eventWebsite,omitempty"`
	// Tag(s) representing the intended audience for the event
	Audience string `json:"audience,omitempty"`
	// Cost of the event
	Cost string `json:"cost,omitempty"`
	// Event host information
	Host string `json:"host,omitempty"`
	// Unique Id of the location hosting the event
	LocationId int32 `json:"locationId,omitempty"`
	// Display name of the location hosting the event
	LocationName string `json:"locationName,omitempty"`
	// Date item last updated
	UpdatedDate time.Time `json:"updatedDate,omitempty"`
	// Description content for the event, often includes HTML markup
	Content string `json:"content,omitempty"`
}
