/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Locpick struct {
	UserLatitude string `json:"user_latitude,omitempty"`
	UserLongitude string `json:"user_longitude,omitempty"`
}
