/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An Important Date is an event at a time that has significance to the Waterloo community
type ImportantDate struct {
	// Unique, non-persistent Api Id for this resource
	Id int32 `json:"id,omitempty"`
	// Name/Title of the Important Date
	Name string `json:"name,omitempty"`
	// Optional description of the Important Date, can contain markup
	Description string `json:"description,omitempty"`
	// The type category this Important Date belongs to
	ImportantDateType string `json:"importantDateType,omitempty"`
	// Details about terms, dates, and special notes
	Details []ImportantDateDetails `json:"details,omitempty"`
	// Keywords associated with the Important Date
	Keywords []string `json:"keywords,omitempty"`
	// Audiences associated with the Important Date
	Audiences []string `json:"audiences,omitempty"`
}
