/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Value struct {
	Index int32 `json:"index,omitempty"`
	Follow int32 `json:"follow,omitempty"`
	Noindex int32 `json:"noindex,omitempty"`
	Nofollow int32 `json:"nofollow,omitempty"`
	Noarchive int32 `json:"noarchive,omitempty"`
	Nosnippet int32 `json:"nosnippet,omitempty"`
	Noodp int32 `json:"noodp,omitempty"`
	Noydir int32 `json:"noydir,omitempty"`
	Noimageindex int32 `json:"noimageindex,omitempty"`
	Notranslate int32 `json:"notranslate,omitempty"`
}
