/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Model representing a Location for the Buildings dataset
type Location struct {
	// Unique identifier for this building
	BuildingId string `json:"buildingId,omitempty"`
	// Alpha-numeric building code
	BuildingCode string `json:"buildingCode,omitempty"`
	// Unofficial, alpha-numeric building code that represents the parent location
	ParentBuildingCode string `json:"parentBuildingCode,omitempty"`
	// Display name of the building
	BuildingName string `json:"buildingName,omitempty"`
	// Unofficial, collection of alternate building display names
	AlternateBuildingNames []string `json:"alternateBuildingNames,omitempty"`
	// Latitude co-ordinate of this location
	Latitude float64 `json:"latitude,omitempty"`
	// Longitude co-ordinate of this location
	Longitude float64 `json:"longitude,omitempty"`
}
