/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RdfMapping struct {
	Rdftype []string `json:"rdftype,omitempty"`
	Title *Title `json:"title,omitempty"`
	Created *Created `json:"created,omitempty"`
	Changed *Changed `json:"changed,omitempty"`
	Body *Body `json:"body,omitempty"`
	Uid *Uid `json:"uid,omitempty"`
	Name *Name `json:"name,omitempty"`
	CommentCount *CommentCount `json:"comment_count,omitempty"`
	LastActivity *LastActivity `json:"last_activity,omitempty"`
}
