/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Data describing scheduling and availability data for a Class
type ClassSchedule struct {
	// Course identifier number, not unique
	CourseId string `json:"courseId,omitempty"`
	// Course offer number identifier for this class
	CourseOfferNumber int32 `json:"courseOfferNumber,omitempty"`
	// Session code number for this class
	SessionCode string `json:"sessionCode,omitempty"`
	// Number identifying the section of this class
	ClassSection int32 `json:"classSection,omitempty"`
	// Waterloo academic term code
	TermCode string `json:"termCode,omitempty"`
	// Identifier for the class meeting this schedule data relates to
	ClassMeetingNumber int32 `json:"classMeetingNumber,omitempty"`
	// The date this schedule begins
	ScheduleStartDate time.Time `json:"scheduleStartDate,omitempty"`
	// The date this schedule ends
	ScheduleEndDate time.Time `json:"scheduleEndDate,omitempty"`
	// The start time of this class
	ClassMeetingStartTime time.Time `json:"classMeetingStartTime,omitempty"`
	// The end time of this class
	ClassMeetingEndTime time.Time `json:"classMeetingEndTime,omitempty"`
	// A code representing the days the class schedule takes place during the week
	ClassMeetingDayPatternCode string `json:"classMeetingDayPatternCode,omitempty"`
	// A Y|N per day representation of the class schedule taking place during the week
	ClassMeetingWeekPatternCode string `json:"classMeetingWeekPatternCode,omitempty"`
	// REMOVED for privacy. Building and room name for the location of this class schedule
	LocationName string `json:"locationName,omitempty"`
}
