/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Model representing a Site on the Waterloo CMS
type Site struct {
	// Unique, numeric site ID
	SiteId int32 `json:"siteId,omitempty"`
	// Relative URI of the site from the root uWaterloo CMS domain
	RelativeUri string `json:"relativeUri,omitempty"`
	// Display name of the Site
	Name string `json:"name,omitempty"`
	// If available, the department owner code for this Site. Can loosely map to Academic Groups.
	OwnerUnitCode string `json:"ownerUnitCode,omitempty"`
	// Short name of the department owner for this Site. See OwnerUnitCode for more.
	OwnerUnitNameShort string `json:"ownerUnitNameShort,omitempty"`
	// Full name of the department owner for this Site. See OwnerUnitCode for more.
	OwnerUnitNameFull string `json:"ownerUnitNameFull,omitempty"`
	// If available, the faculty owner code for this Site. Can loosely map to Academic Organization.
	OwnerGroupCode string `json:"ownerGroupCode,omitempty"`
	// The tag describing the association of the owner department, such as academic, research, and more.
	OwnerType string `json:"ownerType,omitempty"`
}
