/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FoodServicesFranchise struct {
	Id int32 `json:"id,omitempty"`
	Self string `json:"self,omitempty"`
	Name string `json:"name,omitempty"`
	Logo *Logo `json:"logo,omitempty"`
	Combos []Combo `json:"combos,omitempty"`
	Individualitems []IndividualItem `json:"individualitems,omitempty"`
	Addons []Addon `json:"addons,omitempty"`
}
