/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Model representing a Location for the Buildings dataset in GEO JSON format
type LocationGeo struct {
	// Type property of GEO JSON collection
	Type_ string `json:"type,omitempty"`
	// Features of this collection
	Features []Feature `json:"features,omitempty"`
}
