/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FranchiseMenu struct {
	Vid string `json:"vid,omitempty"`
	Uid string `json:"uid,omitempty"`
	Title string `json:"title,omitempty"`
	Log string `json:"log,omitempty"`
	Status string `json:"status,omitempty"`
	Comment string `json:"comment,omitempty"`
	Promote string `json:"promote,omitempty"`
	Sticky string `json:"sticky,omitempty"`
	Vuuid string `json:"vuuid,omitempty"`
	Nid string `json:"nid,omitempty"`
	Type_ string `json:"type,omitempty"`
	Language string `json:"language,omitempty"`
	Created string `json:"created,omitempty"`
	Changed string `json:"changed,omitempty"`
	Tnid string `json:"tnid,omitempty"`
	Translate string `json:"translate,omitempty"`
	Uuid string `json:"uuid,omitempty"`
	RevisionTimestamp string `json:"revision_timestamp,omitempty"`
	RevisionUid string `json:"revision_uid,omitempty"`
	FieldAddons *Object `json:"field_addons,omitempty"`
	FieldCombos *FieldCombos `json:"field_combos,omitempty"`
	FieldFranchiseLogo *FieldFranchiseLogo `json:"field_franchise_logo,omitempty"`
	FieldIndividualItems *Object `json:"field_individual_items,omitempty"`
	TitleField *TitleField `json:"title_field,omitempty"`
	Metatags *Metatags `json:"metatags,omitempty"`
	RdfMapping *RdfMapping `json:"rdf_mapping,omitempty"`
	Path *Path `json:"path,omitempty"`
	Translations *Translations `json:"translations,omitempty"`
	TitleOriginal string `json:"title_original,omitempty"`
	EntityTranslationHandlerId string `json:"entity_translation_handler_id,omitempty"`
	TitleLanguage string `json:"title_language,omitempty"`
	Cid string `json:"cid,omitempty"`
	LastCommentTimestamp string `json:"last_comment_timestamp,omitempty"`
	LastCommentName *Object `json:"last_comment_name,omitempty"`
	LastCommentUid string `json:"last_comment_uid,omitempty"`
	CommentCount string `json:"comment_count,omitempty"`
	Name string `json:"name,omitempty"`
	Picture string `json:"picture,omitempty"`
	Data string `json:"data,omitempty"`
	UwPageSettingsNodeEnable string `json:"uw_page_settings_node_enable,omitempty"`
	WorkbenchModeration *WorkbenchModeration `json:"workbench_moderation,omitempty"`
}
