/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Path struct {
	Pid string `json:"pid,omitempty"`
	Source string `json:"source,omitempty"`
	Alias string `json:"alias,omitempty"`
	Language string `json:"language,omitempty"`
	Pathauto string `json:"pathauto,omitempty"`
}
