/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Cuisine struct {
	Id string `json:"id,omitempty"`
	Self string `json:"self,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
}
