/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Und1 struct {
	Fid string `json:"fid,omitempty"`
	Uid string `json:"uid,omitempty"`
	Filename string `json:"filename,omitempty"`
	Uri string `json:"uri,omitempty"`
	Filemime string `json:"filemime,omitempty"`
	Filesize string `json:"filesize,omitempty"`
	Status string `json:"status,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
	Uuid string `json:"uuid,omitempty"`
	RdfMapping []Object `json:"rdf_mapping,omitempty"`
	FocalPoint string `json:"focal_point,omitempty"`
	Alt string `json:"alt,omitempty"`
	Title string `json:"title,omitempty"`
	Width string `json:"width,omitempty"`
	Height string `json:"height,omitempty"`
}
