/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type En struct {
	Value string `json:"value,omitempty"`
	Format *Object `json:"format,omitempty"`
	SafeValue string `json:"safe_value,omitempty"`
}
