/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CommentCount struct {
	Predicates []string `json:"predicates,omitempty"`
	Datatype string `json:"datatype,omitempty"`
}
