/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// An academic Term at Waterloo, a defined period of time that is used by classes and similar
type Term struct {
	// Code that describes this Term
	TermCode string `json:"termCode,omitempty"`
	// The Name for this Term, most often the displayed name
	Name string `json:"name,omitempty"`
	// The short form name for this Term
	NameShort string `json:"nameShort,omitempty"`
	// The date and time from which the Term begins, inclusive
	TermBeginDate time.Time `json:"termBeginDate,omitempty"`
	// The date and time on which the Term ends, inclusive
	TermEndDate time.Time `json:"termEndDate,omitempty"`
	// The date and time at which the term is 60% complete, used for standing, withdrawal, and penalties
	SixtyPercentCompleteDate time.Time `json:"sixtyPercentCompleteDate,omitempty"`
	// The academic year to which this Term belongs
	AssociatedAcademicYear int32 `json:"associatedAcademicYear,omitempty"`
}
