/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents Geometry data of the Feature
type Geometry struct {
	// Type of geometry
	Type_ string `json:"type,omitempty"`
	// Latitude and Longitude collection of this location
	Coordinates []float64 `json:"coordinates,omitempty"`
}
