/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type En2 struct {
	EntityType string `json:"entity_type,omitempty"`
	EntityId string `json:"entity_id,omitempty"`
	RevisionId string `json:"revision_id,omitempty"`
	Language string `json:"language,omitempty"`
	Source string `json:"source,omitempty"`
	Uid string `json:"uid,omitempty"`
	Status string `json:"status,omitempty"`
	Translate string `json:"translate,omitempty"`
	Created string `json:"created,omitempty"`
	Changed string `json:"changed,omitempty"`
}
