/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OutletLocation struct {
	Lid string `json:"lid,omitempty"`
	Name string `json:"name,omitempty"`
	Street string `json:"street,omitempty"`
	Additional string `json:"additional,omitempty"`
	City string `json:"city,omitempty"`
	Province string `json:"province,omitempty"`
	PostalCode string `json:"postal_code,omitempty"`
	Country string `json:"country,omitempty"`
	Latitude string `json:"latitude,omitempty"`
	Longitude string `json:"longitude,omitempty"`
	Source string `json:"source,omitempty"`
	IsPrimary string `json:"is_primary,omitempty"`
	Locpick *Locpick `json:"locpick,omitempty"`
	ProvinceName string `json:"province_name,omitempty"`
	CountryName string `json:"country_name,omitempty"`
}
