/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An Academic Organization at Waterloo is similar to a department
type AcademicOrganization struct {
	// Unique Code of this Academic Organization
	Code string `json:"code,omitempty"`
	// The Name for this Academic Organization, most often the display name
	Name string `json:"name,omitempty"`
	// The short description for this Academic Organization
	Description string `json:"description,omitempty"`
	// The formal description for this Academic Organization, most often used in official capacity
	DescriptionFormal string `json:"descriptionFormal,omitempty"`
	// The Code for the Campus that this Academic Organization is assigned to
	AssociatedCampusCode string `json:"associatedCampusCode,omitempty"`
}
