/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FoodServicesOutlet struct {
	Id int32 `json:"id,omitempty"`
	Self string `json:"self,omitempty"`
	Name string `json:"name,omitempty"`
	Image []FoodServicesOutletImage `json:"image,omitempty"`
	Photo *FoodServicesOutletPhoto `json:"photo,omitempty"`
	Features string `json:"features,omitempty"`
	Outlettype []OutletType `json:"outlettype,omitempty"`
	Outletlocation string `json:"outletlocation,omitempty"`
	Locationlink *LocationLink `json:"locationlink,omitempty"`
	Description string `json:"description,omitempty"`
	Location []OutletLocation `json:"location,omitempty"`
	Summary string `json:"summary,omitempty"`
	Cuisine []Cuisine `json:"cuisine,omitempty"`
	Openinghours []OpeningHour `json:"openinghours,omitempty"`
	Paymentaccepted []PaymentAccepted `json:"paymentaccepted,omitempty"`
	Closed []Closed `json:"closed,omitempty"`
	Hourschange []HoursChange `json:"hourschange,omitempty"`
	Notice string `json:"notice,omitempty"`
	Franchisemenu []FranchiseMenu `json:"franchisemenu,omitempty"`
	Sticky string `json:"sticky,omitempty"`
	Created string `json:"created,omitempty"`
}
