/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Addon struct {
	Name string `json:"name,omitempty"`
	Photo *Object `json:"photo,omitempty"`
	Price string `json:"price,omitempty"`
	Calories *Object `json:"calories,omitempty"`
}
