/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Data object representing a University of Waterloo paid holiday
type PaidHoliday struct {
	// Date of the paid holiday event
	HolidayDate time.Time `json:"holidayDate,omitempty"`
	// Name of the paid holiday
	Name string `json:"name,omitempty"`
}
