/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LocationLink struct {
	Url string `json:"url,omitempty"`
	Title *Object `json:"title,omitempty"`
	Attributes []Object `json:"attributes,omitempty"`
	OriginalTitle *Object `json:"original_title,omitempty"`
	OriginalUrl string `json:"original_url,omitempty"`
}
