/*
 * Waterloo OpenData API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type HoursChange struct {
	Value time.Time `json:"value,omitempty"`
	Value2 time.Time `json:"value2,omitempty"`
	TimezoneDb string `json:"timezone_db,omitempty"`
	DateType string `json:"date_type,omitempty"`
}
